# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: old_style 1.4.1 ruby lib

Gem::Specification.new do |s|
  s.name = "old_style"
  s.version = "1.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["hayduke19us"]
  s.date = "2014-02-11"
  s.description = "Rails helper. Finds the irrelevent styles in your \n  stylesheet and generates a html report to keep you informed."
  s.email = "hayduke19us@gmail.com"
  s.executables = ["old_style"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/stylesheets/fake3.css.scss",
    "app/assets/stylesheets/fake4.css",
    "app/views/fake/fake.html.erb",
    "app/views/fake/fake2.html",
    "base.css",
    "bin/old_style",
    "lib/format.rb",
    "lib/html_parser.rb",
    "lib/load_dir.rb",
    "lib/old_style.rb",
    "lib/parse_dir.rb",
    "old_style.gemspec",
    "old_style/index.css",
    "old_style/index.html",
    "test/helper.rb",
    "test/test_format.rb",
    "test/test_html_parser.rb",
    "test/test_load_dir.rb",
    "test/test_old_style.rb",
    "test/test_parse_dir.rb"
  ]
  s.homepage = "http://github.com/hayduke19us/old_style"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Get rid of those old css styles"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<css_parser>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<css_parser>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<css_parser>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

